### ISSUE TITLE
Evoland 2 (Adobe AIR)

### ISSUE THREAD

**Issue by Firlaev-Hans** [lightspark/lightspark#885]
### What is the purpose of your issue?
Site Support Request: Lightspark does not work correctly on a specific ~~website~~ game

---

#### If it is possible to download the file and run it with the command line, please provide a link to the file here:
It's a paid game so I can't just provide it here. I could privately provide the game files to a developer if I had a way to privately contact them.

#### Provide the complete set of instructions required to reproduce the problem:

1. Get the files for the windows version of the Evoland 2 (there's no Linux version this time), available on [GOG](https://www.gog.com/game/evoland_2) or [Steam](https://store.steampowered.com/app/359310/) (**not** the "Legendary Edition" re-release which doesn't use Adobe AIR)
2. Open `game.dat` with Lightspark with the `--air` argument

#### What kind of failure is your issue?
**Fault**: You receive a black window instead of the flash content with a white text such as ``We're sorry, Lightspark encountered a yet unsupported Flash file``

#### Provide the Lightspark version

Output of ``lightspark -v``:

```
Lightspark version 0.8.5-1310-g33e89018
```

#### What operating system are you are running on?

Arch Linux

#### How are you are running Lightspark?

Lightspark executable on the command line

#### Which of these actions you have taken to help debug the problem?

- [ ] I attached a screen shot of the problem to this issue
- [ ] I have a backtrace listing and pasted it in the bottom section of this issue (*hint: hitting Ctrl-C after a crash will copy it to the clipboard*)
- [x] I have reproduced the problem using the Lightspark command line executable
- [x] I ran `lightspark -l 4` on the command line and am attaching logs to this issue (*hint: if they are too big, zip them*)

---

### Description of your issue
Evoland 2 is another Adobe AIR game just like [Evoland 1](https://github.com/lightspark/lightspark/issues/825), but unlike Evoland 1, it does not run in standalone Flash player as it uses some AIR-specific features like flash.filesystem, because the SWF (.dat) only contains the Actionscripts while the assets are stored in a separate .pak file. It is also quite a bit more complex (but at least also more interesting and fun to play) than its predecessor, in fact it might be one of the biggest Flash/AIR games out there, so sorry for opening this potentially huge can of worms :D
When trying to run the game in Lightspark with `--air` I get:
```
INFO: throwing exception:0 id:1009 Error #1009: Cannot access a property or method of a null object reference.
    at haxe::Unserializer/()
    at Class/run()
    at Class/load()
    at boot_7bd6/init()
    at boot_7bd6/start()
    at boot_7bd6/()

INFO: dynamic cast:flash.filesystem::File
ERROR: Unhandled ActionScript exception in VM Enum not found hxsl.Type
INFO: dynamic cast:String
INFO: ~RenderThread this=0x5648ba81af90
```
[Here's the full log with `-l 4`](https://github.com/lightspark/lightspark/files/7833029/log.zip)

**Comment by eiglow** [comment]
Given that commit emails are accessible by simply cloning the repo and checking `git log`, I feel comfortable posting the email @dbluelle who you can send the game files to:
```
dbluelle (at) onlinehome.de
```

**Comment by Firlaev-Hans** [comment]
>commit emails are accessible by simply cloning the repo and checking `git log`

Yeah I realized that yesterday as well. I'll send it to him now.

**Comment by Firlaev-Hans** [comment]
Right now I get a different Actionscript Exception, instead of
`ERROR: Unhandled ActionScript exception in VM Enum not found hxsl.Type`
I now get
`ERROR: Unhandled ActionScript exception in VM res.pak does not exists`
res.pak is the file containing all the game assets, and it very much does exist, in the same folder as game.dat, just like it should

**Comment by dbluelle** [comment]
OK, it's working now, although it's still very slow...

**Comment by Firlaev-Hans** [comment]
I just did a little testing for me it's not actually slow, although CPU usage is quite high.
Unsurprisingly I have found several issues already which I'll list shortly, though surprisingly big parts of the game are already working as expected!
Here's an archive of existing save games of several random stages of the game that I already had: [save.tar.gz](https://github.com/lightspark/lightspark/files/8104624/save.tar.gz)
Note that these go in a "save" folder in the location of the game files, not in the Flash local storage location like Evoland 1. Lightspark can read these savegames, but it can't write them.
I named them after the scheme `place_timeline_gamestate`. In this game you travel a lot between multiple different timelines: ancient -> Monochrome graphics, like in the introduction
past -> 8 bit color graphics
present -> 16 bit color graphics, like after the intro cutscene when you wake up
future -> 3D graphics
And for reference I'm just going to link this [detailed walkthrough](https://steamcommunity.com/sharedfiles/filedetails/?id=507708552) of the entire game.
 
But now, the issues:
- Saving does not work, but loading existing savegames created by Adobe AIR does
- High CPU usage and climbing memory usage, as mentioned above
- The memory usage rises particularly quickly in the Noria mines (`noriamines_past_entrance`) and Lightspark eventually crashed here even though I _didn't_ run out of memory yet. (Note: to continue in this part, after the dialog, press tab twice to switch the companion to the demon and then charge an attack by holding shift to destroy the stone block.) A suspicious warning that appeared many times in the terminal was: 
```
[mp3 @ 0x7f03c3581100] invalid concatenated file detected - using bitrate for duration
[mp3float @ 0x7f0342c395c0] Could not update timestamps for skipped samples.
```
- Various menus cause big parts of the screen to flash and stop being updated until the game is restarted (e. g. the escape menu once you press tab once, but also various other inevitable menus that come up during the game, e. g. when entering text)
- In the introduction cutscene (after the monochrome gameplay intro), certain elements are not rendered (e. g. the sky), and there's a rather long pause with a black screen between each scene, so the music doesn't line up with the images anymore. Very High CPU usage during the cutscene.
- Some sounds are cut off (I first noticed while fighting the spiders in the monochrome introduction, but it happens at other parts too). Related to the warnings above?
- occasional white flashes of the entire screen, similar to Evoland 1
- (This also happens in the Windows version of Evoland 1:) Pressing escape brings up the menu. But since the game starts up in fullscreen, escape also switches Lightspark to windowed mode. This is kind of annoying.
- Gameplay problem: When you load the `ghostforest_past_entrance` savegame, after some dialog, the game softlocks; you'll see a ghost in the top right corner which is supposed to move to the center along with several other ghosts, and the cutscene should continue. But in Lightspark the ghost just stays in that corner and you can't do anything to continue. 
There are [script errors in the terminal](https://github.com/lightspark/lightspark/files/8104622/ghostlog.tar.gz) (see the bottom of this file)
- 3D mode / The future: **does not work** / causes an unhandled exception:

3D Genova (`genova_future_prefinalboss`):
```
VerifyError: Error #1021: Error #1021: At least one branch target was not on a valid instruction in the method.
    at map::ZLevel3d/init()
    at Game/initLevel()
    at Game/changeLevel()
    at Game/init()
    at global/()
    at Game/loadAssets()
    at Game/setup()
    at haxe::Timer/()
    at /()
```
3D World map (`worldmap_future_prefinalboss`):
```
VerifyError: Error #1021: Error #1021: At least one branch target was not on a valid instruction in the method.
    at map::WorldMap3d/init()
    at map::WorldMap3d/init()
    at Game/initLevel()
    at Game/changeLevel()
    at Game/init()
    at global/()
    at Game/loadAssets()
    at Game/setup()
    at haxe::Timer/()
    at /()
```
I expect there to be several more issues considering this game's complexity, which we'll find after more testing, but first the savegames and the menu glitch will have to be fixed (and ideally the memory leaks) otherwise testing will be a pain / nearly impossible.
I'm also curious whether the 3D part will have issues with the depth buffer again but it probably will since this game is made using the same "heaps.io" haxe game engine, and even Running Fred, made in Unity, appears to suffer from this.

**Comment by Firlaev-Hans** [comment]
[a28ca0d](https://github.com/lightspark/lightspark/commit/a28ca0d7cdcdf481234f097168c78a57c0a32f6b) kinda broke the game, Lightspark now segfaults as soon as you press any key in the main menu.
[crash.txt](https://github.com/lightspark/lightspark/files/8133095/crash.txt)

**Comment by dbluelle** [comment]
I've fixed the VerifyError so that the 3D World works. 
The "End of file" exceptions can be ignored, the game just catches that and uses it to detect if the file is read completely...

**Comment by Firlaev-Hans** [comment]
Well ain't this a surprise, we've got a working depth buffer in this game. Good work so far!
However, performance just regressed by **_a lot_**, even the 2D parts now run at <15FPS now when they were mostly smooth before, and new memory leaks seem to have been introduced (memory usage quickly climbs in any scene).

There are some graphical glitches in the 3D world, though not as many as I would've expected:
**Original Game (`genova_future_prefinalboss`):**
![Evoland2Genova](https://user-images.githubusercontent.com/61254500/155775073-d0cbe0de-1d17-453d-85d0-7a7440c0cfaf.jpg)
**Lightspark:**
![LightsparkEvoland2Genova](https://user-images.githubusercontent.com/61254500/155775009-fe3966bb-3c34-4da0-982c-5404e7959db0.jpg)
- Stretched ground texture, similar to the Diablo section of Evoland 1
- The water looks strange, instead of those little white cartoony waves we got really huge white spots, also the water is not blurred (can be seen on the 3D world map as well)
- No depth of field effect (compare the upper right corner of the screenshots)

And performance is atrocious. It feels even lower than what MangoHUD reports here. On the 3D world map the CPU is pretty much maxed out, but even in Genova City (and other environments besides the world map) performance is just as bad and neither CPU usage nor GPU usage is terribly high there.

**Comment by Firlaev-Hans** [comment]
The [max recursion depth increase](https://github.com/lightspark/lightspark/commit/ff3f3da03493711a05ddf0ab3f81e3987dc4a5fa) fixed some of the script errors causing soft locks, but not all of them. I tried increasing it further to 1024 and even that wasn't enough.
After setting it to 2048 though all soft locks I've encountered were gone, so I suggest that as a new maximum.

**Comment by Firlaev-Hans** [comment]
I've been meaning to do some further testing with this game (switching to the original executable every time I'd encounter a road-blocking issue) but I ran into another regression randomly causing a sound-related exception every so often at literally any part of the game, and it makes testing almost impossible:
```
TypeError: Error #1010: Error #1010: A term is undefined and has no properties.
    at hxd.snd::Worker/readMessage()
    at flash.system::MessageChannel/()
```
I also have a more detailed [level 4 log](https://github.com/lightspark/lightspark/files/8521080/log_hxd_snd_Worker.txt) but I'm not sure how useful that really is.
A _somewhat_ reliable way to reproduce it is to load my `save2.dat.worldmap_future_prefinalboss` savegame from the archive in my previous comment and pressing shift to mount the airship.
Another huge annoyance is that Lightspark leaks several hundred megabytes of memory every time a new 3D scenery loads (i. e. whenever you enter the world map or enter some place from the world map), so I have to restart Lightspark all the time.

**Comment by Firlaev-Hans** [comment]
The fix for the "Papunika flicker glitch" from Evoland 1 actually fixed the flickering in this game when opening the inventory as well, however it still doesn't look correct, as the top most item is not visible, the second one only partially, and instead some items at the bottom are visible that shouldn't be:
![LightsparkEvoland2InventorySortOfFixed](https://user-images.githubusercontent.com/61254500/180058625-1089d100-9824-4ce0-ba87-9988469118dd.jpg)
But at least the game doesn't become unplayable any more when opening the inventory. This was a significant issue before that made some parts of the game unplayable.

Unfortunately the exception from my last comment still happens regularly so doing more testing is basically impossible with this popping up after just a few seconds or minutes.
I was going to check if the text input fields (when you get to name a character) are working now since they had the same issue as the inventory, but due this exception, I couldn't get to one..
The memory leaks when loading a switching the 3D scenery is also still there.

**Comment by dbluelle** [comment]
It generally runs, but has some graphical glitches.
Also the sound currently doesn't work, but I've not figured out why.

**Comment by Firlaev-Hans** [comment]
There are also still game-breaking script errors, e. g. the one from [this comment](https://github.com/lightspark/lightspark/issues/885#issuecomment-1054543987), or being unable to load a savegame from the sewers (`Unhandled ActionScript exception in VM EUnknownVariable(grav)`)
And the graphical glitches seem to have gotten worse? E. g. in the 3D world, water isn't rendered at all anymore.

**Comment by dbluelle** [comment]
I've fixed a stupid mistake when setting the the max_recursion_depth, so the stack overflow errors should be gone.

**Comment by dbluelle** [comment]
I've fixed the sound issue, so music is playing now.

**Comment by dbluelle** [comment]
> ![LightsparkEvoland2InventorySortOfFixed](https://user-images.githubusercontent.com/61254500/180058625-1089d100-9824-4ce0-ba87-9988469118dd.jpg) 

This is fixed.
Also the Water now has "waves", but unfortunately it is rendered above everything else...
